// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showOverlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dismissOverlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleOverlay() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_overlay") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultOverlayShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_overlay_shortcut");
},
async updateOverlayShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_overlay_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSnapshot(data: SnapshotInput) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snapshot", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLatestSnapshot() : Promise<Result<Snapshot | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_latest_snapshot") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSnapshots(limit: number, offset: number, project: string | null) : Promise<Result<Snapshot[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_snapshots", { limit, offset, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProjects() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_projects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWeeklyReport(weekOffset: number) : Promise<Result<WeeklyReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_weekly_report", { weekOffset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getResumeCard() : Promise<Result<ResumeCard | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_resume_card") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markResumed(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_resumed", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getInterruptionLog(date: string | null, project: string | null) : Promise<Result<InterruptionLogResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_interruption_log", { date, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDayTimeline(date: string, project: string | null) : Promise<Result<DayTimelineEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_day_timeline", { date, project }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if the app has macOS Accessibility permission (required for global shortcuts).
 * Returns true on non-macOS platforms.
 */
async checkAccessibility() : Promise<boolean> {
    return await TAURI_INVOKE("check_accessibility");
},
/**
 * Open macOS System Settings → Privacy → Accessibility.
 */
async openAccessibilitySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_accessibility_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSnapshots(path: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_snapshots", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSnapshots(path: string) : Promise<Result<ImportResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_snapshots", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppState(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_state", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppState(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_state", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppPreferences = { theme: string; overlay_shortcut: string | null }
export type DayCount = { day: number; day_name: string; count: number; time_lost_seconds: number }
export type DayTimelineEntry = { snapshot: Snapshot; gap_before_seconds: number | null }
export type EnergyCount = { energy_state: string; count: number }
export type HourCount = { hour: number; count: number }
export type ImportResult = { imported: number; skipped: number }
export type InterruptionLogEntry = { snapshot: Snapshot; time_away_seconds: number | null; interruption_display: string }
export type InterruptionLogResult = { entries: InterruptionLogEntry[]; total_interruptions: number; total_time_lost_seconds: number }
export type ResumeCard = { snapshot: Snapshot; away_duration_seconds: number; is_stale: boolean }
export type Snapshot = { id: number; current_task: string; progress_note: string; next_step: string; energy_state: string; interruption_type: string | null; interruption_note: string | null; linked_project: string | null; open_questions: string | null; created_at: string; resumed_at: string | null; resume_duration_seconds: number | null }
export type SnapshotInput = { current_task: string; progress_note: string; next_step: string; energy_state: string; interruption_type: string | null; interruption_note: string | null; linked_project: string | null; open_questions: string | null }
export type TypeBreakdown = { interruption_type: string; count: number; time_lost_seconds: number }
export type WeeklyReport = { week_start: string; week_end: string; total_interruptions: number; total_time_lost_seconds: number; avg_gap_seconds: number; most_common_type: string | null; by_day: DayCount[]; by_type: TypeBreakdown[]; by_energy: EnergyCount[]; by_hour: HourCount[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
