use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        app_state_cmd, export_cmd, hotkey, import_cmd, log_cmd, overlay, preferences, reports_cmd,
        resume_cmd, snapshot_cmd,
    };

    Builder::<tauri::Wry>::new().commands(collect_commands![
        // Preferences
        preferences::load_preferences,
        preferences::save_preferences,
        // Overlay
        overlay::show_overlay,
        overlay::dismiss_overlay,
        overlay::toggle_overlay,
        overlay::get_default_overlay_shortcut,
        overlay::update_overlay_shortcut,
        // Snapshots
        snapshot_cmd::save_snapshot,
        snapshot_cmd::get_latest_snapshot,
        snapshot_cmd::get_snapshots,
        snapshot_cmd::get_projects,
        // Reports
        reports_cmd::get_weekly_report,
        // Resume
        resume_cmd::get_resume_card,
        resume_cmd::mark_resumed,
        // Log & Timeline
        log_cmd::get_interruption_log,
        log_cmd::get_day_timeline,
        // Accessibility
        hotkey::check_accessibility,
        hotkey::open_accessibility_settings,
        // Export / Import
        export_cmd::export_snapshots,
        import_cmd::import_snapshots,
        // App State
        app_state_cmd::get_app_state,
        app_state_cmd::set_app_state,
    ])
}

pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
    }
}
